//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guoli.Official.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int Id { get; set; }
        public int JobTypeId { get; set; }
        public int DepartmentId { get; set; }
        public string WorkingPlace { get; set; }
        public int HiringNumber { get; set; }
        public string Responsibilities { get; set; }
        public string Requirements { get; set; }
        public string Preference { get; set; }
        public string AsumePosts { get; set; }
        public System.DateTime AddTime { get; set; }
        public bool IsDeleted { get; set; }
    }
}
